package com.example.rider.model.dto;

/**
 * Rider Registration Request
 * excludes default and autogenerated attributes of Rider
 */
public class RegisterDTO {

    private String name;
	private String phone;
	private String email;
	private String password;
    private String city;

    public RegisterDTO() {}

    public String getName() {
        return name;
    }

    public String getPhone() {
        return phone;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCity() {
        return city;
    }

    @Override
    public String toString() {
        return "RegisterDTO{" +
                "name=" + name +
                ", phone=" + phone +
                ", email=" + email +
                ", city=" + city +
                '}';
    }
}
