package com.example.rider.model;

/**
 * Rider Registration Request
 * excludes default and autogenerated attributes of Rider
 */
public class RiderRegReq {

	private String name;
	private String phone;
	private String email;
	private String password;

    public String getName() {
        return name;
    }

    public String getPhone() {
        return phone;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }
}
