package com.example.rider.model;

/**
 * Rider Registration Request
 * excludes default and autogenerated attributes of Rider
 */
public class RiderRegDTO {

    private String name;
	private String phone;
	private String email;
	private String password;

    public RiderRegDTO() {}

    public String getName() {
        return name;
    }

    public String getPhone() {
        return phone;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "RiderRegDTO{" +
                "name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                (email!=null?(", email='" + email ):"") + '}';
    }
}
